version: '3.8'
services:
  visiotechapi:
    image: ${DOCKER_REGISTRY-}visiotechapi
    build:
      context: .
      dockerfile: Visiotech API/Dockerfile
    environment:
      - ASPNETCORE_ENVIROMENT=Development
    ports:
      - "8000:8000"
    networks:
      - app
  
  postgres:
    container_name: postgres_db
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: Bz3kW.AJT7MV8t@
      POSTGRES_BD: bd
    networks:
      - app

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    ports: 
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - postgres
    networks:
      - app

networks:
  app:
    driver: bridge